$lines = @(
'import { readFileSync, existsSync, readdirSync, mkdirSync, writeFileSync, unlinkSync } from "node:fs";',
'import { join, resolve } from "node:path";',
'import { writeAudit, createAuditEntry } from "./audit.js";',
'',
'const DELEGATE_DIR = ".devspace";',
'const CEO_DIR = join(DELEGATE_DIR, "ceo");',
'const RUNS_DIR = join(DELEGATE_DIR, "runs");',
'const USER_ANSWERS_DIR = join(DELEGATE_DIR, "user_answers");',
'',
'function safePath(requestedPath: string): string | null {',
'  const full = resolve(DELEGATE_DIR, requestedPath);',
'  const base = resolve(DELEGATE_DIR);',
'  if (!full.startsWith(base)) return null;',
'  if (full.includes("..")) return null;',
'  return full;',
'}',
'',
'function safeRead(filePath: string): { ok: boolean; content?: string; error?: string } {',
'  const safe = safePath(filePath);',
'  if (!safe) return { ok: false, error: "Path traversal rejected" };',
'  if (!existsSync(safe)) return { ok: false, error: `File not found: ${filePath}` };',
'  try {',
'    return { ok: true, content: readFileSync(safe, "utf-8") };',
'  } catch (e) {',
'    return { ok: false, error: `Read error: ${e instanceof Error ? e.message : String(e)}` };',
'  }',
'}',
'',
'function readJsonSafe(filePath: string): { ok: boolean; data?: unknown; error?: string } {',
'  const result = safeRead(filePath);',
'  if (!result.ok) return { ok: false, error: result.error };',
'  try {',
'    return { ok: true, data: JSON.parse(result.content!) };',
'  } catch {',
'    return { ok: false, error: "Invalid JSON" };',
'  }',
'}'
)
$lines -join "`n" | Set-Content -Path "d:\Code\git\devspace\src\mcp\handlers.ts" -Encoding UTF8NoBOM
Write-Host "Part 1 written"
